### ISSUE TITLE
Lib not found in the "Adafruit CircuitPython Bundle"

### ISSUE THREAD

**Issue by michael-land** [adafruit/Adafruit_CircuitPython_BLE_File_Transfer#15]
On the release page, it mentions 

`To use in CircuitPython, simply install the [Adafruit CircuitPython Bundle](https://circuitpython.org/libraries).`

I don't see this package in the bundle.

any help would be appreciate

**Comment by tannewt** [comment]
For now you can get it here: https://github.com/adafruit/Adafruit_CircuitPython_BLE_File_Transfer/releases/tag/4.0.0

We'll get it added to the bundle soon too.

**Comment by xiaoyu-tamu** [comment]
Ah, thanks

**Comment by tekktrik** [comment]
Adding this as a first good issue in preparation for Hacktoberfest!

If anyone wants to do this, the instructions for adding this to the Adafruit CircuitPython Bundle can be found here:
https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/sharing-in-the-community-bundle

**Comment by zachariahpifer** [comment]
Working on this at PyCon 2023

**Comment by jposada202020** [comment]
Fixed https://github.com/adafruit/Adafruit_CircuitPython_Bundle/pull/406. Verified in 2023/04/27 Circuitpythonbundle. thanks @elpekenin for noticing this. :)
