### ISSUE TITLE
Ble_file_transfer_simpletest.py not working on Feather nRF52840 express

### ISSUE THREAD

**Issue by Angelo904** [adafruit/Adafruit_CircuitPython_BLE_File_Transfer#23]
NOTE: I’m a beginner so I might have missed something! 😅

I installed the package without problems on my windows 11 pc and then tried to run the simpletest example code on my Feather nRF 52840 express.
The code runs without errors but the MU serial console shows repeatedly the “disconnected, scanning” message and nothing else happens. While the code is running I see the Feather on the Bluefruit Connect App on my IPhone7 Plus, but it won’t connect. Just says “connecting…” forever.
Any help is very welcome!
Angelo

**Comment by tekktrik** [comment]
I think the file transfer here is a custom solution and not necessarily and file transfer protocol that Bluefruit Connect App uses, if I remember correctly.  So it would work with another microcontroller using this library but not necessarily the app (or a computer).  Is that correct, @tannewt?

**Comment by Angelo904** [comment]
Based on what 

> I think the file transfer here is a custom solution and not necessarily and file transfer protocol that Bluefruit Connect App uses, if I remember correctly. So it would work with another microcontroller using this library but not necessarily the app (or a computer). Is that correct, @tannewt?

So in case it helps, what I’m trying to do ultimately is read a .txt file stored in the Feather from my iPhone. 
If @tekktrik is correct and I cannot do it with this package would there be another solution?

**Comment by tannewt** [comment]
@Angelo904 To read files over BLE, you don't need to have any specific user code running. CircuitPython makes this protocol available from internal code. Check out this learn guide that documents how to use File Glider to send and read files over BLE: https://learn.adafruit.com/how-to-transfer-files-to-a-circuit-playground-bluefruit-using-the-fileglider-app

**Comment by Angelo904** [comment]
@tannewt, this is great! I downloaded the Glider app and it works perfectly for my purposes. I’ll do some more studying to get everything smoothed out but I should be ok. 
If I can make a suggestion, I would advertise more the File Glider on the Adafruit BLE guides. On the Feather learning guide I believe only the Bluefruit Connect App is mentioned. 
Thanks again! 
Angelo

**Comment by tannewt** [comment]
> If I can make a suggestion, I would advertise more the File Glider on the Adafruit BLE guides. On the Feather learning guide I believe only the Bluefruit Connect App is mentioned.

Yup! I agree. We're just getting there. :-) It's all new.
