### ISSUE TITLE
Add code eval command?

### ISSUE THREAD

**Issue by EternityForest** [adafruit/Adafruit_CircuitPython_BLE_File_Transfer#24]
While it's not technically file transfer related, almost all of the existing stuff references date and time and would be more useful with a reliable standard way to set it, and adding more protocols and connections to constrained devices might not be the best plan.

Other issues have also mentioned formatting the filesystem, and interactive console use almost always seems to be involved when debugging.

Having a general purpose way to remote execute some Python would solve a lot of problems:

* Set time
* Get time(Use device as clock for RasPi)
* Control GPIO
* Format the filesystem
* Run the code you just uploaded
* Uncompress with zlib
* Find out what protocol version is in use
* Get remaining storage space
* Firmware updates

You could have a persistent locals() environment to run the code in, that resets itself on disconnect to free up RAM.

**Comment by tannewt** [comment]
File transfer is designed to be agnostic to where it is used. If you want CircuitPython specific stuff, then you can do it over the serial BLE link.
