### ISSUE TITLE
Information about transfer speed

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [adafruit/Adafruit_CircuitPython_BLE_File_Transfer#25]
Can you please add some information about the transfer speed you achieved (respectively which speed can be expected)?

**Comment by tannewt** [comment]
Its been a while since I tested. IIRC is was a couple kb per second.

**Comment by D-r-P-3-p-p-3-r** [comment]
Ok, thanks. That's what we're getting. So I don't have to search a bottle neck or a problem.
